input_dir_lexicon = "/home/carolina/corpora/lexicons/"
input_dir_lexicon_vad = "/home/carolina/corpora/lexicons/vad_lexicons/"
input_dir_embeddings = "/home/carolina/corpora/embeddings/"
input_dir_senti_embeddings = "/home/carolina/corpora/embeddings/emotions_embedings/"
input_dir_emo_corpora = "/home/carolina/corpora/emotion_datasets/"
local_dir_embeddings = "/home/carolina/embeddings/"